"""
Air Quality Constants
"""
BREEZOMETER_AQI_FEATURE = "breezometer_aqi"
LOCAL_AQI_FEATURE = "local_aqi"
POLLUTANTS_CONCENTRATIONS_FEATURES = "pollutants_concentrations"
ALL_POLLUTANTS_CONCENTRATIONS_FEATURES = "all_pollutants_concentrations"
POLLUTANTS_AQI_INFORMATION = "pollutants_aqi_information"
AIR_QUALITY_API_FEATURES = (
    BREEZOMETER_AQI_FEATURE,
    LOCAL_AQI_FEATURE,
    POLLUTANTS_CONCENTRATIONS_FEATURES,
    ALL_POLLUTANTS_CONCENTRATIONS_FEATURES,
    POLLUTANTS_AQI_INFORMATION,
)
HISTORICAL_AIR_QUALITY_API_FEATURES = (BREEZOMETER_AQI_FEATURE,)
