name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - uses: actions/cache@v2
        with:
          path: ~/.tox
          key: ${{ env.pythonLocation}}-${{ hashFiles('tox.ini') }}-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}
      - name: Lint Files (flake8)
        run: tox -e pep8
